# Default language if you have a multi-language setup
DefaultContentLanguage = "en"

baseURL = "https://example.com"

theme = "amperage"

pygmentsUseClasses = true

# Number of posts shown per page (dafault: 10)
paginate = 3

# Language sections
[languages]
    [languages.en]
        contentDir = "content"
        languageName = "English"
        languageCode = "en"
        title = "Bits n' Bytes"
        description = "Welcome to my site!"
        weight = 1

    # Hope I got this one rite
    [languages.zh]
        contentDir = "content/zh"
        languageName = "中文" # probably fucked this too, sorry
        languageCode = "zh"
        title = "Bits n' Bytes"
        description = "欢迎来到我的网站"
        weight = 2

# Menu elements
# Menu elements
[[languages.en.menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/sophia-zeng-13506b159/"
    weight = 8

[[languages.en.menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Darkpoppy"
    weight = 9

[[languages.en.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

[[languages.zh.menu.main]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/sophia-zeng-13506b159/"
    weight = 8

[[languages.zh.menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/Darkpoppy"
    weight = 9

[[languages.zh.menu.main]]
    identifier = "about"
    name = "关于"
    url = "zh/about"
    weight = 10

# Enable only tags taxonomy
[taxonomies]
    tag = "tags"

[params]
    copyright = "Sophia Zeng" # Name shown on footer copyright
    themeColor = "#333" # Theme color displayed on mobile browsers

    # Default AMP components for the whole site
    ampElements = ["amp-iframe", "amp-analytics", "amp-social-share", "amp-install-serviceworker"]

    # Google Analytics code
    # googleAnalytics = "UA-xxxxxxxxx-x"

    # Adsense publisher code
    # adsensePublisher = "ca-pub-123456789"

    # Comments Iframe URL
    # commentsEmbedUrl = "https://comments.example.com"

    # Social sites for metatags
    # facebookSite = "example"
    # twitterSite = "@example"

    # Structured data elements
    # socialProfiles = ["https://twitter.com/example","https://www.linkedin.com/in/example/","https://github.com/example"]

    # alternatePageName = "Amperage example"
    # organizationLogo = "/logo.png"
    # organizationName = "Asur"

    publisherName = "Sophia Zeng"
    # publisherLogo = "/logo-amp-article.png"
    # publisherLogoWidth = 600
    # publisherLogoHeight = 60

[markup]
    defaultMarkdownHandler = "blackfriday"